# Generated by Django 4.2.6 on 2023-10-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Date',
            field=models.DateField(default='1999-02-20'),
            preserve_default=False,
        ),
    ]
